### ISSUE TITLE
emitPluginDocuments broken after Gatsby upgrade

### ISSUE THREAD

**Issue by nibtime** [cometkim/gatsby-plugin-typegen#113] opened 2020-10-17 20:42 UTC
Hi @cometkim,

still enjoying your plugin, DX is superb and I didn't have a single problem with it until now 💯. I recently upgraded Gatsby (you can find my environment info below) and after that, `emitPluginDocuments` stopped working. I suspect they changed some internals of the development server.

### Expected Result

`emitPluginDocuments: { "__generated__/gatsby-plugin-documents.graphql": true }` results in a `__generated__/gatsby-plugin-documents.graphql` file with plugin dependencies (like fragments of `gatsby-transformer-sharp)`

### Actual Result 

File is not generated. There is no report of `[typegen] Emit Gatsby plugin documents` when starting develop

<details>
<summary>short debugging gif</summary>

![debug_typegen](https://user-images.githubusercontent.com/52962482/96353047-d6e88b80-10c8-11eb-8f09-6ee3912a7667.gif)

</details>

### Environment

<details>
<summary>yarn list | grep gatsby</summary>

```
❯ yarn list | grep "gatsby"
├─ @iacm-med/site-gatsby@0.3.2
│  ├─ gatsby-image@^2.4.1
│  ├─ gatsby-plugin-env-variables@^1.0.1
│  ├─ gatsby-plugin-lodash@^3.3.13
│  ├─ gatsby-plugin-manifest@^2.2.41
│  ├─ gatsby-plugin-mdx@^1.2.47
│  ├─ gatsby-plugin-nprogress@^2.1.19
│  ├─ gatsby-plugin-offline@^3.2.32
│  ├─ gatsby-plugin-preact@^3.1.26
│  ├─ gatsby-plugin-preload-fonts@^1.0.27
│  ├─ gatsby-plugin-purgecss@^4.0.0
│  ├─ gatsby-plugin-react-helmet@^3.0.4
│  ├─ gatsby-plugin-remove-serviceworker@^1.0.0
│  ├─ gatsby-plugin-sass@^2.0.7
│  ├─ gatsby-plugin-sharp@^2.2.9
│  ├─ gatsby-plugin-tinacms@~0.1.37
│  ├─ gatsby-plugin-typegen@^2.2.1
│  ├─ gatsby-plugin-typescript@^2.1.5
│  ├─ gatsby-plugin-webpack-bundle-analyser-v2@^1.1.8
│  ├─ gatsby-remark-copy-linked-files@^2.0.7
│  ├─ gatsby-remark-images@^3.1.6
│  ├─ gatsby-remark-relative-images@^0.2.1
│  ├─ gatsby-source-filesystem@^2.0.26
│  ├─ gatsby-source-stripe@^3.0.4
│  ├─ gatsby-tinacms-git@~0.4.11
│  ├─ gatsby-tinacms-json@~0.8.22
│  ├─ gatsby-tinacms-mdx@~0.31.0
│  ├─ gatsby-transformer-json@^2.2.25
│  ├─ gatsby-transformer-remark@^2.6.9
│  ├─ gatsby-transformer-sharp@^2.1.9
│  ├─ gatsby@^2.24.78
├─ babel-preset-gatsby@0.5.14
│  ├─ gatsby-core-utils@^1.3.23
│  └─ gatsby-legacy-polyfills@^0.0.5
├─ gatsby-cli@2.12.108
│  ├─ gatsby-core-utils@^1.3.23
│  ├─ gatsby-recipes@^0.2.31
│  ├─ gatsby-telemetry@^1.3.38
├─ gatsby-core-utils@1.3.23
├─ gatsby-design-tokens@2.0.13
├─ gatsby-graphiql-explorer@0.4.15
├─ gatsby-image@2.4.2
├─ gatsby-interface@0.0.193
│  ├─ gatsby-design-tokens@^2.0.2
├─ gatsby-legacy-polyfills@0.0.5
├─ gatsby-link@2.4.15
├─ gatsby-page-utils@0.2.28
│  ├─ gatsby-core-utils@^1.3.23
├─ gatsby-plugin-env-variables@1.0.2
├─ gatsby-plugin-lodash@3.3.13
├─ gatsby-plugin-manifest@2.4.2
│  ├─ gatsby-core-utils@^1.2.1
│  ├─ gatsby-core-utils@1.2.1
├─ gatsby-plugin-mdx@1.2.47
│  ├─ gatsby-core-utils@^1.3.23
├─ gatsby-plugin-nprogress@2.3.1
├─ gatsby-plugin-offline@3.2.33
│  ├─ gatsby-core-utils@^1.3.23
├─ gatsby-plugin-page-creator@2.3.32
│  ├─ gatsby-page-utils@^0.2.28
├─ gatsby-plugin-preact@3.3.1
├─ gatsby-plugin-preload-fonts@1.2.1
│  ├─ gatsby-core-utils@^1.2.1
│  ├─ gatsby-core-utils@1.2.1
├─ gatsby-plugin-purgecss@4.0.1
├─ gatsby-plugin-react-helmet@3.3.1
├─ gatsby-plugin-remove-serviceworker@1.0.0
├─ gatsby-plugin-sass@2.3.1
├─ gatsby-plugin-sharp@2.6.1
│  ├─ gatsby-core-utils@^1.2.1
│  ├─ gatsby-core-utils@1.2.1
├─ gatsby-plugin-tinacms@0.1.37
├─ gatsby-plugin-typegen@2.2.1
├─ gatsby-plugin-typescript@2.4.2
├─ gatsby-plugin-utils@0.2.32
├─ gatsby-plugin-webpack-bundle-analyser-v2@1.1.9
├─ gatsby-react-router-scroll@3.0.14
├─ gatsby-recipes@0.2.31
│  ├─ gatsby-core-utils@^1.3.23
│  ├─ gatsby-interface@^0.0.193
│  ├─ gatsby-telemetry@^1.3.38
├─ gatsby-remark-copy-linked-files@2.3.2
├─ gatsby-remark-images@3.3.1
│  ├─ gatsby-core-utils@^1.2.1
│  ├─ gatsby-core-utils@1.2.1
├─ gatsby-remark-relative-images@0.2.3
├─ gatsby-source-filesystem@2.3.1
│  ├─ gatsby-core-utils@^1.2.1
│  ├─ gatsby-core-utils@1.2.1
├─ gatsby-source-stripe@3.0.7
│  ├─ gatsby-core-utils@1.2.1
│  ├─ gatsby-source-filesystem@2.1.55
│  ├─ gatsby-source-filesystem@2.1.55
│  │  ├─ gatsby-core-utils@^1.0.33
├─ gatsby-telemetry@1.3.38
│  ├─ gatsby-core-utils@^1.3.23
├─ gatsby-tinacms-git@0.4.11
├─ gatsby-tinacms-json@0.8.22
├─ gatsby-tinacms-mdx@0.31.0
├─ gatsby-transformer-json@2.4.1
├─ gatsby-transformer-remark@2.8.7
│  ├─ gatsby-core-utils@^1.2.1
│  ├─ gatsby-core-utils@1.2.1
├─ gatsby-transformer-sharp@2.5.1
├─ gatsby@2.24.78
│  ├─ babel-preset-gatsby@^0.5.14
│  ├─ gatsby-cli@^2.12.108
│  ├─ gatsby-core-utils@^1.3.23
│  ├─ gatsby-graphiql-explorer@^0.4.15
│  ├─ gatsby-legacy-polyfills@^0.0.5
│  ├─ gatsby-link@^2.4.15
│  ├─ gatsby-plugin-page-creator@^2.3.32
│  ├─ gatsby-plugin-typescript@^2.4.22
│  ├─ gatsby-plugin-typescript@2.4.22
│  ├─ gatsby-plugin-utils@^0.2.32
│  ├─ gatsby-react-router-scroll@^3.0.14
│  ├─ gatsby-telemetry@^1.3.38
```
</details>

<details>
<summary>gatsby info</summary>

```
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 10.20.1 - /tmp/yarn--1602967108564-0.22010673723337582/node
    Yarn: 1.22.4 - /tmp/yarn--1602967108564-0.22010673723337582/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 68.8.0esr
```
</details>

<details>
<summary>VS Code devcontainer</summary>

```Dockerfile
ARG NODE_VERSION=10.20
FROM node:${NODE_VERSION}-buster-slim

# Install System Dependencies
RUN apt-get update && apt-get install -y \
   curl git git-lfs ssh python3 python3-crcmod libvips-dev zsh gnupg build-essential \
   && apt-get clean

# Install Google Cloud SDK
# https://github.com/GoogleCloudPlatform/cloud-sdk-docker/blob/a896d312e7e2f244e6f636b5129ba65f669c6288/alpine/Dockerfile
ARG CLOUD_SDK_VERSION=287.0.0
ENV CLOUD_SDK_VERSION=$CLOUD_SDK_VERSION
ENV CLOUDSDK_PYTHON=python3
ENV PATH /google-cloud-sdk/bin:$PATH

RUN curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz \
    && tar xzf google-cloud-sdk-$CLOUD_SDK_VERSION-linux-x86_64.tar.gz \
    && rm google-cloud-sdk-$CLOUD_SDK_VERSION-linux-x86_64.tar.gz \
    && gcloud config set core/disable_usage_reporting true \
    && gcloud config set component_manager/disable_update_check true \
    && gcloud config set metrics/environment github_docker_image \
    && gcloud --version

# Install Pulumi
ARG PULUMI_VERSION=2.1.0
ENV PULUMI_VERSION=$PULUMI_VERSION
ENV PATH /pulumi:$PATH

RUN curl -O https://get.pulumi.com/releases/sdk/pulumi-v$PULUMI_VERSION-linux-x64.tar.gz \
  && tar xzf pulumi-v$PULUMI_VERSION-linux-x64.tar.gz \
  && rm pulumi-v$PULUMI_VERSION-linux-x64.tar.gz \
  && pulumi version

# Install and configure oh-my-zsh
ENV ZSH=/usr/share/oh-my-zsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
COPY .zshrc ~
RUN chsh -s $(which zsh)

CMD ["zsh"]

```
</details>

**Comment by cometkim** [comment] 2020-10-18 21:26
@nibtime Thank you for the detailed report. I will fix it as soon as possible.

Until the fixed version is released, you can use documents generated in the previous version and turn the option off temporarily.

**Comment by cometkim** [comment] 2020-10-22 22:24
> I suspect they changed some internals of the development server.

@edykim has a good explanation on https://github.com/cometkim/gatsby-plugin-typegen/pull/114 for the cause of this problem.

The behavior seems to have changed on development as you suspect.

Fragments are loaded on the `onPreExtractQueries` hook.

And the hook executed **after** the `onPostBootstrap` hook on `gatsby develop`:
![image](https://user-images.githubusercontent.com/9696352/96936442-06502b80-1501-11eb-8e7b-3d44c7ccf20d.png)

Also **before** the hook on `gatsby build`:
![image](https://user-images.githubusercontent.com/9696352/96936689-7fe81980-1501-11eb-8487-5458a30a67c2.png)

what an inconsistency :shrug:

**Comment by cometkim** [comment] 2020-10-23 01:47
it duplicates a ticket: #98

**Comment by cometkim** [comment] 2022-03-14 20:45
This has been fixed in v3 (currently RC release available)

**Closed as completed by cometkim** 2022-03-14 20:45 UTC
Labels: bug
